### ISSUE TITLE
TensorFlow 2 compatibility

### ISSUE THREAD

**Issue by jackgle** [MiviaLab/DENet#2]
It would be great if the DELayer was updated to be compatible with TF2

**Comment by rohanali1798** [comment]
Hello @jackgle I'm trying to run the example but I face many errors like **cannot import name 'Layer' from 'tensorflow.python.keras.engine.base_layer' (/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py)**. can you help me run the example? 
Many thanks.

**Comment by robertanto** [comment]
Which version of Tensorflow and Keras are you using? @rohanali1798

**Comment by rohanali1798** [comment]
@robertanto I just replicated the example. The libraries along with versions are mentioned in the requirements.txt file so I just installed that but I always get that kind of error that I mentioned above,

**Comment by Nazmus-Sanib** [comment]
I used the following code block in the google colab and the error was removed:

!pip3 uninstall -y tensorflow

!pip3 insatll tensorflow==2.0.0


!pip3 install -r requirements.txt


To install the above libraries from the Linux terminal, just remove the ! from the beginning of each code.
To install from the windows terminal, use pip instead of pip3.
